version: '3.8'
services:
    gnbsim:
        container_name: gnbsim
        image: gnbsim:develop
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=1
            - TAC=0x00a000
            - SST=222
            - SD=00007b
            - PagingDRX=v32
            - RANUENGAPID=0
            - IMEISV=35609204079514
            - MSIN=0000000031
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=default
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - NGAPPeerAddr=192.168.70.132
            - GTPuLocalAddr=192.168.70.136 # spgwu-tiny-upf
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.136
        healthcheck:
            test: /bin/bash -c "ifconfig gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external:
            name: demo-oai-public-net
# Incase the user wants docker-compose to create a bridge rather than creating the bridge manually then uncomment the below lines
#     public_net:
#         driver: bridge
#         name: demo-oai-public-net
#         ipam:
#             config:
#                 - subnet: 192.168.70.128/26
#         driver_opts:
#             com.docker.network.bridge.name: "demo-oai"