version: '3.8'
services:
    mysql:
        container_name: "mysql"
        image: mysql:5.7
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_core:
                ipv4_address: 192.168.71.131
    oai-amf:
        container_name: "oai-amf"
        image: oai-amf:develop
        environment:
            - TZ=Europe/paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            - SST_0=222
            - SD_0=123
            - SST_1=1
            - SD_1=12
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            - SMF_INSTANCE_ID_0=1
            - SMF_IPV4_ADDR_0=192.168.71.133
            - SMF_HTTP_VERSION_0=v1
            - SMF_INSTANCE_ID_1=2
            - SMF_IPV4_ADDR_1=0.0.0.0
            - SMF_HTTP_VERSION_1=v1
            - MYSQL_SERVER=192.168.71.131
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - OPERATOR_KEY=63bfa50ee6523365ff14c1f45f88737d
            - NRF_IPV4_ADDRESS=0.0.0.0
            - NRF_PORT=80
            - NF_REGISTRATION=no
            - SMF_SELECTION=no
            - NRF_API_VERSION=v1
            - AUSF_IPV4_ADDRESS=127.0.0.1
            - AUSF_PORT=80
            - AUSF_API_VERSION=v1
        depends_on:
            - vpp-upf
            - oai-ext-dn
            - mysql
        volumes:
            - ./amf-healthcheck.sh:/openair-amf/bin/amf-healthcheck.sh
        healthcheck:
            test: /bin/bash -c "/openair-amf/bin/amf-healthcheck.sh"
            interval: 10s
            timeout: 15s
            retries: 5
        networks:
            public_net_core:
                ipv4_address: 192.168.71.132
    oai-smf:
        container_name: "oai-smf"
        image: oai-smf:vpp-upf
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=192.168.18.129
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.71.132
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - UDM_IPV4_ADDRESS=127.0.0.1
            - UDM_PORT=80
            - UDM_API_VERSION=v1
            - UPF_IPV4_ADDRESS=192.168.71.202
            - NRF_IPV4_ADDRESS=0.0.0.0
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - REGISTER_NRF=no
            - DISCOVER_UPF=no
            - USE_NETWORK_INSTANCE=yes
        extra_hosts:
            - "gw1.vppupf.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.71.202"
        depends_on:
            - oai-amf
        volumes:
             - ./smf-healthcheck.sh:/openair-smf/bin/smf-healthcheck.sh
        healthcheck:
             test: /bin/bash -c "/openair-smf/bin/smf-healthcheck.sh"
             interval: 10s
             timeout: 5s
             retries: 5
        networks:
            public_net_core:
                ipv4_address: 192.168.71.133
    vpp-upf:
        image: vpp-upg:develop
        privileged: true
        container_name: vpp-upf
        environment:
            - NWI_CORE=core.oai.org
            - NWI_ACCESS=access.oai.org
            - NWI_SGI=sgi.oai.org
            - GW_ID=1
            - MNC03=95
            - MCC=208
            - REALM=3gppnetwork.org
            - NETWORK_UE_IP=12.1.1.0/24
            - N3_IPV4_ADDRESS_REMOTE=192.168.72.141
            - N3_IPV4_ADDRESS_LOCAL=192.168.72.202
            - N4_IPV4_ADDRESS_REMOTE=192.168.71.133
            - N4_IPV4_ADDRESS_LOCAL=192.168.71.202            
            - N6_IPV4_ADDRESS_REMOTE=192.168.73.135
            - N6_IPV4_ADDRESS_LOCAL=192.168.73.202
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - INTERFACE_ACCESS=eth0
            - INTERFACE_CORE=eth1
            - INTERFACE_SGI=eth2
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_core:
                ipv4_address: 192.168.71.134
            public_net_access:
                ipv4_address: 192.168.72.134
            public_net_sgi_lan:
                ipv4_address: 192.168.73.134
    oai-ext-dn:
        image: ubuntu:bionic
        privileged: true
        container_name: oai-ext-dn
        entrypoint: /bin/bash -c \
              "apt update; apt install -y iptables iproute2 iputils-ping;"\
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.73.202 dev eth0; sleep infinity"
        command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
        depends_on:
            - vpp-upf
        networks:
            public_net_sgi_lan:
                ipv4_address: 192.168.73.135
networks:
    public_net_core:
        name: oai-public-core
        ipam:
            config:
                - subnet: 192.168.71.0/24
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
    public_net_sgi_lan:
        name: oai-public-sgi-lan
        ipam:
            config:
                - subnet: 192.168.73.0/24
        
    
# Incase the user wants docker-compose to create a bridge rather than creating the bridge manually then uncomment the below lines
#     public_net:
#         driver: bridge
#         name: demo-oai-public-net
#         ipam:
#             config:
#                 - subnet: 192.168.71.128/26
#         driver_opts:
#             com.docker.network.bridge.name: "demo-oai"
