apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-health-cm
data:
  {{ (.Files.Glob "scripts/live-ready.sh").AsConfig | indent 2 | trim }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-real-config
data:
  {{ (.Files.Glob "scripts/amf.conf").AsConfig | indent 2 }}

